### ISSUE TITLE
REST-API: Performing a deposit with total_deposit less than current total_deposit returns 200 response

### ISSUE THREAD

**Issue by Dominik1999** [raiden-network/raiden#2630]
## Raiden node returns 200 SUCCESS when setting `total_deposit` to something smaller than current `total_deposit` (withdrawing)

This test runs successfully with a Raiden node.

```      

scenario:
  serial:
         name: Scenario F11 (Depositing negative amount II)
         tasks:
           - open_channel: {from: 0, to: 1, total_deposit: 99_000_000_000_000_000_000}
           - assert: {from: 0, to: 1, total_deposit: 99_000_000_000_000_000_000, balance: 99_000_000_000_000_000_000, state: "opened"} 
           - deposit: {from: 0, to: 1, total_deposit: 1, expected_http_status: 200}
           - assert: {from: 0, to: 1, total_deposit: 99_000_000_000_000_000_000, balance: 99_000_000_000_000_000_000, state: "opened"}

```
Therefore, it is possible to set `total_deposit` to 1 token (the Raiden Node returns code 200) without changing the status of `total_deposit`. 

I used my own token with 18 decimals.
