### ISSUE TITLE
Unify all linting into a pre-commit hook setup

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#3344]
## Problem Definition

[Suggested](https://github.com/raiden-network/raiden/tree/test-review/ob-review#pylint--flake8) to us during our test review. 

Suggestion is to:

- Unify all linting checks (flake8, mypy, pylint) into a common [pre-commit](https://pre-commit.com/) hook setup. Add that to the documentation and contributing guide and ask all developers to be using this. This will make life easier for everyone involved.

**Comment by hackaugusto** [comment]
For reference, this is my current configuration based on @ulope : 

```
exclude: '^$'
fail_fast: false
repos:
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.4.3
    hooks:
      - id: autopep8
  - repo: git://github.com/doublify/pre-commit-isort
    rev: v4.3.0
    hooks:
      - id: isort 
        args: ["--ignore-whitespace", "--settings-path", "./", "--recursive"]
  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v2.3.0.dev0
    hooks:
      - id: pylint
        args: ["--rcfile", ".pylint.rc", "raiden"]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      # - id: double-quote-string-fixer
      - id: end-of-file-fixer
      - id: flake8
        additional_dependencies: ["flake8-bugbear", "flake8-commas", "flake8-tuple", "readme-renderer",]
      - id: mixed-line-ending
      - id: trailing-whitespace
```
