### ISSUE TITLE
Config-file parsing fails on wallet address

### ISSUE THREAD

**Issue by deepbrook** [raiden-network/raiden#5267]
Given the following `docker-compose` file:
```yaml
  raiden:
    image: "raidennetwork:v0.200.0-rc1"
    ports:
      - "5001:5001"
    volumes:
      - "/etc/brainbot/raiden/keystores:/keystores"
      - "/etc/brainbot/raiden:/config"
    command:
      - --config-file=/config/config.toml
    healthcheck:
      test: ["CMD", "curl", "http://localhost:5001"]
      interval: 1m
      timeout: 10s
      retries: 3
    restart: on-failure
```
where `raidennetwork:v0.200.0-rc1` is a docker image built from the github repository at tag `v0.200.0-rc1`, using the dockerfile at https://github.com/raiden-network/raiden/blob/v0.200.0-rc1/docker/Dockerfile, using `ansible==2.8`:
```yaml
---
- name: Pull Raiden Repository
  git:
    repo: "github.com/raiden-network/raiden"
    dest: /tmp/raiden
    version: "v0.200.0-rc1"

- name: Build Image from GIT Repository
  docker_image:
    name: "raidennetowork:v0.200.0-rc1"
    build:
      path: /tmp/raiden
      dockerfile: /tmp/raiden/docker/Dockerfile
      args:
        RAIDENVERSION: "v0.200.0-rc1"
    source: build
    push: no
```

Given the following config file with an invalid password file value:
```toml
eth-rpc-endpoint = "http://parity.goerli.ethnodes.brainbot.com"
network-id = 5
address = "0x09C556bAeb629b48017ea851A22a2A7CE20F9d3F"
password-file = "/config/account.password" # <--- Does NOT exist
api-address = "localhost:5001"
log-file = "/var/log/raiden.log"
matrix-server = "http://transport04.raiden.network"
environment-type = "development"
routing-mode = "local"
log-json = true
sync-check = true
no-web-ui = true
accept-disclaimer = true
keystore-path = '/keystores/'
```

Running `docker-compose up` yields the following:

```bash
root@raiden-goerli-01:~# /usr/local/bin/docker-compose -f /etc/brainbot/containers/raiden/docker-compose.yml up
raiden_raiden_1 is up-to-date
Attaching to raiden_raiden_1
raiden_1  | Error loading config file: /config/config.toml(3, 12): msg
raiden_1  | Error loading config file: /config/config.toml(3, 12): msg
raiden_1  | Error loading config file: /config/config.toml(3, 12): msg
raiden_1  | Error loading config file: /config/config.toml(3, 12): msg
raiden_1  | Error loading config file: /config/config.toml(3, 12): msg
raiden_1  | Error loading config file: /config/config.toml(3, 12): msg
raiden_1  | Error loading config file: /config/config.toml(3, 12): msg
raiden_1  | Error loading config file: /config/config.toml(3, 12): msg
raiden_raiden_1 exited with code 1
```

**Expected result: The cli states that the password file does not exist and exits.**
Actual result: The node crashes with a non-descriptive parser error
